"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";

export default function SignupPage() {
  const { signUp } = useAuth(); const router = useRouter();
  const [form, setForm] = useState({ email: "", password: "", restaurant_name: "", restaurant_email: "", restaurant_phone: "" });
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const update = (field) => (event) => setForm({ ...form, [field]: event.target.value });
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); if (!supabase) { setError("Supabase is not configured. Check your .env.local file."); setBusy(false); return; } try { const data = await signUp(form.email, form.password, { restaurant_name: form.restaurant_name, restaurant_email: form.restaurant_email || null, restaurant_phone: form.restaurant_phone || null }); if (data.session) router.replace("/dashboard"); else setMessage("Check your inbox to confirm your email, then sign in to finish setup."); } catch (requestError) { setError(requestError.message || "Unable to create your workspace."); } finally { setBusy(false); } }
  return <main className="min-h-screen grid lg:grid-cols-2 bg-surface"><section className="grid place-items-center p-6 sm:p-12 order-2 lg:order-1"><div className="w-full max-w-md"><Link href="/" className="font-display font-extrabold text-lg text-ink">Rasoi<span className="text-accent">Saathi</span></Link><p className="font-mono text-xs tracking-widest text-accent mt-16">OWNER ONBOARDING</p><h2 className="font-display text-4xl font-extrabold text-ink mt-4 tracking-tight">Create your workspace</h2><p className="text-muted mt-3">Your Supabase account becomes the owner of this restaurant workspace.</p>{error && <p className="mt-5 rounded-lg bg-red-50 border border-red-200 p-3 text-sm text-red-700">{error}</p>}{message && <p className="mt-5 rounded-lg bg-green-50 border border-green-200 p-3 text-sm text-green-700">{message}</p>}<form onSubmit={submit} className="grid gap-4 mt-8"><label className="grid gap-2 text-sm font-bold text-ink">Your email<input className="rounded-lg border border-border bg-surface-2 px-4 py-3" type="email" required value={form.email} onChange={update("email")} /></label><label className="grid gap-2 text-sm font-bold text-ink">Password<input className="rounded-lg border border-border bg-surface-2 px-4 py-3" type="password" minLength="6" required value={form.password} onChange={update("password")} /></label><label className="grid gap-2 text-sm font-bold text-ink">Restaurant name<input className="rounded-lg border border-border bg-surface-2 px-4 py-3" required value={form.restaurant_name} onChange={update("restaurant_name")} /></label><label className="grid gap-2 text-sm font-bold text-ink">Restaurant email<input className="rounded-lg border border-border bg-surface-2 px-4 py-3" type="email" value={form.restaurant_email} onChange={update("restaurant_email")} /></label><label className="grid gap-2 text-sm font-bold text-ink">Phone<input className="rounded-lg border border-border bg-surface-2 px-4 py-3" value={form.restaurant_phone} onChange={update("restaurant_phone")} /></label><button disabled={busy} className="rounded-lg bg-gradient-to-r from-accent to-accent-2 py-3 text-white font-bold mt-2 disabled:opacity-60">{busy ? "Creating workspace..." : "Create workspace"}</button></form><p className="text-center text-sm text-muted mt-7">Already registered? <Link href="/login" className="font-bold text-accent">Sign in</Link></p></div></section><section className="hidden lg:flex flex-col justify-center p-12 xl:p-20 text-white bg-gradient-to-br from-[#a93220] via-accent to-accent-2 order-1 lg:order-2"><p className="font-mono text-xs tracking-widest text-white/70">START WITH THE WHOLE PICTURE</p><h1 className="font-display font-extrabold text-6xl leading-none tracking-tight mt-5">A steadier service starts with visibility.</h1></section></main>;
}